services:
  api:
    build:
      context: .
      target: production
    image: dolar_api:latest
    container_name: dolar_api
    ports:
      - '${PORT}:${PORT:-3000}'
    env_file:
      - .env
    restart: unless-stopped
